function [freq, t, y] = simulate_repressilator_mod(opt)
    % Set params
    default_params = struct('alpha', 300,...
                            'beta', 0.2,...
                            'alpha0', 0,...
                            'n', 2,...
                            'delta_max', 40,...
                            'D', 0,...
                            'D_half', 8,...
                            'tspan', [0 2000],...
                            'y0', zeros(1, 6));

    if(nargin == 1)
        params = get_params(default_params, opt);
    else
        params = default_params;
    end

    % Run simulation
    [t, y] = ode45(@ODE_repressilator_mod, params.tspan, params.y0, [],...
                   params.alpha, params.beta, params.alpha0, params.n,...
                   params.delta_max, params.D, params.D_half);

    % Find oscillation frequency
    freq = freqfind(t, y, params.tspan(2));
end
